# Generated by Django 4.2 on 2023-05-19 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immo_offres_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
    ]
