# Generated by Django 4.2 on 2023-05-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('nature', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('timestamped', models.CharField(max_length=255)),
                ('date_scraped', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
            ],
        ),
    ]
