# Generated by Django 4.2 on 2023-05-19 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immo_offres_web', '0002_alter_article_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table=None,
        ),
    ]
